// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file order.proto (package order.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file order.proto.
 */
export const file_order: GenFile = /*@__PURE__*/
  fileDesc("CgtvcmRlci5wcm90bxIIb3JkZXIudjEiQwoSQ3JlYXRlT3JkZXJSZXF1ZXN0EgoKAmlkGAEgASgJEg8KB3Byb2R1Y3QYAiABKAkSEAoIcXVhbnRpdHkYAyABKAUiNgoTQ3JlYXRlT3JkZXJSZXNwb25zZRIOCgZzdGF0dXMYASABKAkSDwoHbWVzc2FnZRgCIAEoCTJaCgxPcmRlclNlcnZpY2USSgoLQ3JlYXRlT3JkZXISHC5vcmRlci52MS5DcmVhdGVPcmRlclJlcXVlc3QaHS5vcmRlci52MS5DcmVhdGVPcmRlclJlc3BvbnNlYgZwcm90bzM");

/**
 * @generated from message order.v1.CreateOrderRequest
 */
export type CreateOrderRequest = Message<"order.v1.CreateOrderRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string product = 2;
   */
  product: string;

  /**
   * @generated from field: int32 quantity = 3;
   */
  quantity: number;
};

/**
 * Describes the message order.v1.CreateOrderRequest.
 * Use `create(CreateOrderRequestSchema)` to create a new message.
 */
export const CreateOrderRequestSchema: GenMessage<CreateOrderRequest> = /*@__PURE__*/
  messageDesc(file_order, 0);

/**
 * @generated from message order.v1.CreateOrderResponse
 */
export type CreateOrderResponse = Message<"order.v1.CreateOrderResponse"> & {
  /**
   * @generated from field: string status = 1;
   */
  status: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message order.v1.CreateOrderResponse.
 * Use `create(CreateOrderResponseSchema)` to create a new message.
 */
export const CreateOrderResponseSchema: GenMessage<CreateOrderResponse> = /*@__PURE__*/
  messageDesc(file_order, 1);

/**
 * @generated from service order.v1.OrderService
 */
export const OrderService: GenService<{
  /**
   * @generated from rpc order.v1.OrderService.CreateOrder
   */
  createOrder: {
    methodKind: "unary";
    input: typeof CreateOrderRequestSchema;
    output: typeof CreateOrderResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_order, 0);

