// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file product.proto (package product, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateProductRequest, CreateProductResponse, GetAllProductsRequest, GetAllProductsResponse, GetProductRequest, GetProductResponse } from "./product_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service product.ProductService
 */
export const ProductService = {
  typeName: "product.ProductService",
  methods: {
    /**
     * @generated from rpc product.ProductService.CreateProduct
     */
    createProduct: {
      name: "CreateProduct",
      I: CreateProductRequest,
      O: CreateProductResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.ProductService.GetProduct
     */
    getProduct: {
      name: "GetProduct",
      I: GetProductRequest,
      O: GetProductResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.ProductService.GetAllProducts
     */
    getAllProducts: {
      name: "GetAllProducts",
      I: GetAllProductsRequest,
      O: GetAllProductsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

