// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file product.proto (package product, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file product.proto.
 */
export const file_product: GenFile = /*@__PURE__*/
  fileDesc("Cg1wcm9kdWN0LnByb3RvEgdwcm9kdWN0ImUKFENyZWF0ZVByb2R1Y3RSZXF1ZXN0Eg0KBXNrdWlkGAEgASgJEhMKC2JhcmNvZGVfcG9zGAIgASgJEhQKDHByb2R1Y3RfbmFtZRgDIAEoCRITCgttZXJjaGFudF9pZBgEIAEoCSKIAQoVQ3JlYXRlUHJvZHVjdFJlc3BvbnNlEg0KBXNrdWlkGAEgASgJEhMKC2JhcmNvZGVfcG9zGAIgASgJEhQKDHByb2R1Y3RfbmFtZRgDIAEoCRITCgttZXJjaGFudF9pZBgEIAEoCRIPCgdzdWNjZXNzGAUgASgIEg8KB21lc3NhZ2UYBiABKAkiIgoRR2V0UHJvZHVjdFJlcXVlc3QSDQoFc2t1aWQYASABKAkihQEKEkdldFByb2R1Y3RSZXNwb25zZRINCgVza3VpZBgBIAEoCRITCgtiYXJjb2RlX3BvcxgCIAEoCRIUCgxwcm9kdWN0X25hbWUYAyABKAkSEwoLbWVyY2hhbnRfaWQYBCABKAkSDwoHc3VjY2VzcxgFIAEoCBIPCgdtZXNzYWdlGAYgASgJIhcKFUdldEFsbFByb2R1Y3RzUmVxdWVzdCJbCgpQcm9kdWN0RHRvEg0KBXNrdWlkGAEgASgJEhMKC2JhcmNvZGVfcG9zGAIgASgJEhQKDHByb2R1Y3RfbmFtZRgDIAEoCRITCgttZXJjaGFudF9pZBgEIAEoCSJhChZHZXRBbGxQcm9kdWN0c1Jlc3BvbnNlEiUKCHByb2R1Y3RzGAEgAygLMhMucHJvZHVjdC5Qcm9kdWN0RHRvEg8KB3N1Y2Nlc3MYAiABKAgSDwoHbWVzc2FnZRgDIAEoCTL6AQoOUHJvZHVjdFNlcnZpY2USTgoNQ3JlYXRlUHJvZHVjdBIdLnByb2R1Y3QuQ3JlYXRlUHJvZHVjdFJlcXVlc3QaHi5wcm9kdWN0LkNyZWF0ZVByb2R1Y3RSZXNwb25zZRJFCgpHZXRQcm9kdWN0EhoucHJvZHVjdC5HZXRQcm9kdWN0UmVxdWVzdBobLnByb2R1Y3QuR2V0UHJvZHVjdFJlc3BvbnNlElEKDkdldEFsbFByb2R1Y3RzEh4ucHJvZHVjdC5HZXRBbGxQcm9kdWN0c1JlcXVlc3QaHy5wcm9kdWN0LkdldEFsbFByb2R1Y3RzUmVzcG9uc2VCFKoCEVByb2R1Y3RDcmVhdGUuQXBpYgZwcm90bzM");

/**
 * @generated from message product.CreateProductRequest
 */
export type CreateProductRequest = Message<"product.CreateProductRequest"> & {
  /**
   * @generated from field: string skuid = 1;
   */
  skuid: string;

  /**
   * @generated from field: string barcode_pos = 2;
   */
  barcodePos: string;

  /**
   * @generated from field: string product_name = 3;
   */
  productName: string;

  /**
   * @generated from field: string merchant_id = 4;
   */
  merchantId: string;
};

/**
 * Describes the message product.CreateProductRequest.
 * Use `create(CreateProductRequestSchema)` to create a new message.
 */
export const CreateProductRequestSchema: GenMessage<CreateProductRequest> = /*@__PURE__*/
  messageDesc(file_product, 0);

/**
 * @generated from message product.CreateProductResponse
 */
export type CreateProductResponse = Message<"product.CreateProductResponse"> & {
  /**
   * @generated from field: string skuid = 1;
   */
  skuid: string;

  /**
   * @generated from field: string barcode_pos = 2;
   */
  barcodePos: string;

  /**
   * @generated from field: string product_name = 3;
   */
  productName: string;

  /**
   * @generated from field: string merchant_id = 4;
   */
  merchantId: string;

  /**
   * @generated from field: bool success = 5;
   */
  success: boolean;

  /**
   * @generated from field: string message = 6;
   */
  message: string;
};

/**
 * Describes the message product.CreateProductResponse.
 * Use `create(CreateProductResponseSchema)` to create a new message.
 */
export const CreateProductResponseSchema: GenMessage<CreateProductResponse> = /*@__PURE__*/
  messageDesc(file_product, 1);

/**
 * @generated from message product.GetProductRequest
 */
export type GetProductRequest = Message<"product.GetProductRequest"> & {
  /**
   * @generated from field: string skuid = 1;
   */
  skuid: string;
};

/**
 * Describes the message product.GetProductRequest.
 * Use `create(GetProductRequestSchema)` to create a new message.
 */
export const GetProductRequestSchema: GenMessage<GetProductRequest> = /*@__PURE__*/
  messageDesc(file_product, 2);

/**
 * @generated from message product.GetProductResponse
 */
export type GetProductResponse = Message<"product.GetProductResponse"> & {
  /**
   * @generated from field: string skuid = 1;
   */
  skuid: string;

  /**
   * @generated from field: string barcode_pos = 2;
   */
  barcodePos: string;

  /**
   * @generated from field: string product_name = 3;
   */
  productName: string;

  /**
   * @generated from field: string merchant_id = 4;
   */
  merchantId: string;

  /**
   * @generated from field: bool success = 5;
   */
  success: boolean;

  /**
   * @generated from field: string message = 6;
   */
  message: string;
};

/**
 * Describes the message product.GetProductResponse.
 * Use `create(GetProductResponseSchema)` to create a new message.
 */
export const GetProductResponseSchema: GenMessage<GetProductResponse> = /*@__PURE__*/
  messageDesc(file_product, 3);

/**
 * @generated from message product.GetAllProductsRequest
 */
export type GetAllProductsRequest = Message<"product.GetAllProductsRequest"> & {
};

/**
 * Describes the message product.GetAllProductsRequest.
 * Use `create(GetAllProductsRequestSchema)` to create a new message.
 */
export const GetAllProductsRequestSchema: GenMessage<GetAllProductsRequest> = /*@__PURE__*/
  messageDesc(file_product, 4);

/**
 * @generated from message product.ProductDto
 */
export type ProductDto = Message<"product.ProductDto"> & {
  /**
   * @generated from field: string skuid = 1;
   */
  skuid: string;

  /**
   * @generated from field: string barcode_pos = 2;
   */
  barcodePos: string;

  /**
   * @generated from field: string product_name = 3;
   */
  productName: string;

  /**
   * @generated from field: string merchant_id = 4;
   */
  merchantId: string;
};

/**
 * Describes the message product.ProductDto.
 * Use `create(ProductDtoSchema)` to create a new message.
 */
export const ProductDtoSchema: GenMessage<ProductDto> = /*@__PURE__*/
  messageDesc(file_product, 5);

/**
 * @generated from message product.GetAllProductsResponse
 */
export type GetAllProductsResponse = Message<"product.GetAllProductsResponse"> & {
  /**
   * @generated from field: repeated product.ProductDto products = 1;
   */
  products: ProductDto[];

  /**
   * @generated from field: bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message product.GetAllProductsResponse.
 * Use `create(GetAllProductsResponseSchema)` to create a new message.
 */
export const GetAllProductsResponseSchema: GenMessage<GetAllProductsResponse> = /*@__PURE__*/
  messageDesc(file_product, 6);

/**
 * @generated from service product.ProductService
 */
export const ProductService: GenService<{
  /**
   * @generated from rpc product.ProductService.CreateProduct
   */
  createProduct: {
    methodKind: "unary";
    input: typeof CreateProductRequestSchema;
    output: typeof CreateProductResponseSchema;
  },
  /**
   * @generated from rpc product.ProductService.GetProduct
   */
  getProduct: {
    methodKind: "unary";
    input: typeof GetProductRequestSchema;
    output: typeof GetProductResponseSchema;
  },
  /**
   * @generated from rpc product.ProductService.GetAllProducts
   */
  getAllProducts: {
    methodKind: "unary";
    input: typeof GetAllProductsRequestSchema;
    output: typeof GetAllProductsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_product, 0);

